name: namer_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.5
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/ic.png"

flutter:
  assets:
    - assets/images/
