name: breadly
description: "A bread a day keeps the hunger away."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.5
  workmanager: ^0.9.0+3
  android_intent_plus: ^6.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/bread_ic.png"  # base icon (still required)
  adaptive_icon_background: "#795548"  # black background
  adaptive_icon_foreground: "assets/bread_ic.png"  # your white toast icon

flutter:
  assets:
    - assets/images/
  uses-material-design: true
